### ISSUE TITLE
Secure Boot / PC Manger (Windows) 

### ISSUE THREAD

**Issue by juicypop** [profzei/Matebook-X-Pro-2018#101]
I'm having a hard time to figure out what's wrong with my PC Manager.

I noticed a few days ago that I couldn't start it any longer neither install it from scratch. 
After evaluating difrent approaches I ended up enabling secure boot and this way I was able to install PC Manger and access the beloved battery protection settings. 
OK, I went back into my bios, disabled secure boot and got a bummer. I couldn't access battery protection any longer. Also I had to readjust my boot configuration to access OC and catalina again. 
One more try, again I reenabled secure boot reinstalled PC Manger and everything above happened again. 

My question/Problem is, can I have secure boot disabled and access PC Managers battery protection somehow? 

Or did I missed anything that catalina and OC now work with secure boot? 

Any suggestions/help is appreciated. 

This is how it looks like when secure boot is enabled:
![image](https://user-images.githubusercontent.com/25671698/100984005-6697ab80-354a-11eb-893a-2235b534d40c.png)
As you can see the PC Manager icon is blank and opening the pc manager settings throws this error.

**Comment by juicypop** [comment]
I contacted Huawei support if they are aware of this issue.
But honestly I don't think they're gonna fix it instead they'll for sure tell me to enable secure boot back again. I told them this is no solution for me and not acceptable. 

I'll let you know if they respond to my email.

**Comment by juicypop** [comment]
I got a reply they need my S/N and PC Manager version.
I was lazy and tried to get the S/N with msinfo32 and what did i saw there? My Windows identifies itself as a MacBookPro15,2

What happend? I always booted Windows through OpenCore and it appears that OC overrides some crucial system parameters that are essential for PC Manager to work properly.

How did I solved the problem? I booted into windows using fn+f12 selecting Windows Boot Manager.

What are the downsides? I need to fn+f12 each boot to switch between OC and WBM 

@profzei 
I'm not familiar yet with OpenCore, but could we somehow have original Windows parameters when booting Windows from OpenCore?

**Comment by profzei** [comment]
> I'm not familiar yet with OpenCore, but could we somehow have original Windows parameters when booting Windows from OpenCore?

@juicypop Atm, I think the answer is **nope** since OpenCore injects its parameters even before showing its menu picker: this is well documented in [Dortania's guide](https://dortania.github.io/OpenCore-Install-Guide/) but I don't remember where... XD 
In that guide there is also a reference for using BootCamp and (if I understood well...) choosing its entry in OpenCore picker menu but I didn't have time to dig the argument... atm I don't have any time for learning more about it till Christmas holidays where I need to make a very clean install for Big Sur... and therefore experimenting...

**Comment by samwzlim** [comment]
> I got a reply they need my S/N and PC Manager version.
> I was lazy and tried to get the S/N with msinfo32 and what did i saw there? My Windows identifies itself as a MacBookPro15,2
> 
> What happend? I always booted Windows through OpenCore and it appears that OC overrides some crucial system parameters that are essential for PC Manager to work properly.
> 
> How did I solved the problem? I booted into windows using fn+f12 selecting Windows Boot Manager.
> 
> What are the downsides? I need to fn+f12 each boot to switch between OC and WBM
> 
> @profzei
> I'm not familiar yet with OpenCore, but could we somehow have original Windows parameters when booting Windows from OpenCore?

@juicypop I have the exact same issue as you, and it's pretty frustrating as I have to use Windows Boot Manager in order to access PC Manager (I have a Huawei phone so I use PC Manager frequently). In PC Manager, my laptop shows up as MacbookPro15,2.
![image](https://user-images.githubusercontent.com/74489037/103733089-e02c2900-5023-11eb-92f7-06f0fd75c414.png)

I can't access the settings menu, and this will happen:
![image](https://user-images.githubusercontent.com/74489037/103733135-fafe9d80-5023-11eb-87cc-132e1a561df6.png)

I suspect PC Manager requires the laptop id to be a Huawei Matebook in order for it to have all its features working properly. I've tried unistalling PC Manager but can't install it back (no prompts); which suggests that it is unsupported on any other laptop than a Matebook.

**Comment by profzei** [comment]
It should be fixed in next release in this weekend
