### ISSUE TITLE
wifi not working with release 1.8

### ISSUE THREAD

**Issue by juicypop** [profzei/Matebook-X-Pro-2018#112]
hi @profzei, first of all thanks for the new release 👍 

I just tried it out to find my wifi broken again. No matter what I did I couldn't enable it.
Here are all steps that I tried to reenable it:

- replace BOOT & OC with 1.8 release
- setting/removing my serial number
- disabling/enabling SSDT-PS2K
- using your 1.8 stripped AirportItlwm_Catalina.kext / my previous AirtportItlwm.kext (which is working right now with 1.7 release again) ofc I renamed it to AirportItlwm_Catalina.kext
- resetting NVRAM

My MacOS version is Catalina 10.15.7 supplemental 

I'm out of ideas. No matter what I tried, I couldn't get it working on 1.8 release. So I reverted to previous 1.7 with my AirportItlwm.kext which is working fine again.

[FIX]

edit config.plist according:
> Did you apply the step number 7 of the [network section](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/Network) ? The following default settings of config.plist must be changed for Catalina :
> 
> DmgLoading --> from "Any" to "Signed
> SecureBootModel --> from "Disabled" to "Default"

**Comment by profzei** [comment]
@juicypop What you described is quite "strange"... what do I mean?
- in my [release v. 1.7.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) you should find the distinction between `AirportItlwm_Big_Sur` and `AirportItlwm_Catalina` while no reference for `AirportItlwm` itself
- all [release v. 1.8.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) has the same structure as [v. 1.7.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) where I just updated kexts and two SSDTs... this is because v. 1.8.0. is only a **maintenance release**

Honestly I didn't check if new `AirportItlwm_Catalina` (i.e. in v.1.8.0) was working since I'm using Big Sur and I don't maintain simultaneously two different macOS installation on my MBXP but it is build as Big Sur version so it is supposed to be working...
What you could check is the following:
- you could only update, using your current version 1.7.0, the folder named `OC\Kexts` and see if you have any relevant issues
If not, then the issue is not due to new `AirportItlwm_Catalina`

If you need to rename `AirportItlwm_Catalina` as `AirportItlwm` then it means you never used release v. 1.7.0

**Comment by juicypop** [comment]
Than I might have mixed something up.

The last major thing I did was updating clover to open core with your wiki instructions. 
I thought it was 1.7 apperantly it isn't. 

My AirportItlwm is still from the official repository.

**Comment by ldan93** [comment]
Did you apply the step number 7 of the [network section](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/Network) ? The default settings of config.plist must be changed for Catalina :

> 7. Also change your SecureBootModel to allow loading immutablekernel. Warning: if your macOS version >= macOS 11 (KernelCollection) then you don't need to do the following steps!
> Find the following code:
> 
> <dict>
> 	<key>DmgLoading</key>
> 	<string>Any</string>
> 	...
> and change to:
> 
> <dict>
> 	<key>DmgLoading</key>
> 	<string>Signed</string>
> 	...
> Find the following code:
> 
> <dict>
> 	<key>SecureBootModel</key>
> 	<string>Disabled</string>
> 	...
> and change to:
> 
> <dict>
> 	<key>SecureBootModel</key>
> 	<string>Default</string>
> 	...

**Comment by juicypop** [comment]
Thank you @ldan93 that was the missing part :) 👍 

Unfortunately I thought 1.8 might solve my Huawei mouse not being connected, but it still doesn't connect.
At least I'm update to date now :)
