### ISSUE TITLE
Can't change command-option key pair to previous layout

### ISSUE THREAD

**Issue by pablott** [profzei/Matebook-X-Pro-2018#116]
From the 1.8.0 release notes:
`Add SSDT-PS2K for swapping Command and Option keys in default (if not needed, please, set to false the variable Enabled for SSDT-PS2K in ACPI -> Add section)`

But I did exactly that and still get command on windows key and option on Alt.

How can i revert to old layout? This laptop only has one Win key and for my use I prefer having access to two command keys, one on each side.

**Comment by profzei** [comment]
Hi @pablott 
What I can say is it should work since it's working for me...
If it is not working for you I suggest
- set to false `SSDT-PS2K` in `ACPI -> Add` section or if you prefer you could also delete the entry
- then replace `SSDT-KBD` with the same file from [here](https://github.com/profzei/Matebook-X-Pro-2018/issues/92#issuecomment-731758891)
- then replace `VoodooPS2Controller` with the same file from release v. 1.7.0

**Comment by yamanadamnor** [comment]
I can confirm that setting the `Enabled` variable to `false`does not change the layout

**Comment by pablott** [comment]
Hi @profzei for some reason I got a notification for thread closed but not for your comment. I will try the other options in the next few days.

Meanwhile, I'm just changing the layout of CMD and OPTION keys from within Modifier Keys panel inside Keyboard settings. This seems to work without major issue.

**Comment by pablott** [comment]
> Hi @pablott
> What I can say is it should work since it's working for me...
> If it is not working for you I suggest
> 
>     * set to false `SSDT-PS2K` in `ACPI -> Add` section or if you prefer you could also delete the entry
> 
>     * then replace `SSDT-KBD` with the same file from [here](https://github.com/profzei/Matebook-X-Pro-2018/issues/92#issuecomment-731758891)
> 
>     * then replace `VoodooPS2Controller` with the same file from release v. 1.7.0

I tried all of that but get the same behavior (i. e.: keys are always swap and there is only one CMD key assigned to win key). Note that all changes were performed on 1.8.0 base. I don't see any difference.

For now I will revert to 1.8.0 and use keyboard settings to swap keys.

**Comment by profzei** [comment]
@pablott Ok!

**Comment by profzei** [comment]
@pablott 
Found the correct way with SSDT!
Do the following:
- Please, use default 1.8.0 ACPI and Kext folder with default config.plist
- Then replace original `SSDT-PS2K.aml` with the following one
- Obviously disable your keyboard settings to swap the keys
- Reboot your machine... and you should have two CMD keys located on Left-Alt and Right-Alt Gr!

Please, let me know if it works... it should since I checked it!
Happy New Year!
[SSDT-PS2K.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5765101/SSDT-PS2K.aml.zip)
