### ISSUE TITLE
touchscreen and touchpad didn't work after close the lid for 30 minutes

### ISSUE THREAD

**Issue by AustinLeungCK** [profzei/Matebook-X-Pro-2018#127]
the lid is close for like 30 minutes, and repoen it, the trackpad and touchscreen is not working, need to reboot or use mouse.

applied voltagedownshift, disabled herbinate

**Comment by profzei** [comment]
Hi @AustinLeungCK :
- Touchscreen is disabled in release v. 1.8.0 since MultiGPI0 issue in VoodooI2C (this is a general issue not yet fixed by VoodooI2C's developer team)
- Touchpad wake's issue (due to a VoodooI2C's issue... another different from the previous one mentioned above) was already fixed in release v. 1.8.0

Your submit induces me to think you are not using release v. 1.8.0: please see in the homepage in the right side menu...

This induces me also to think whether it is more convenient to delete all the code apart from the Releases section...

Anyway in next days I'll upload a new release with all my documented work (see Changelog) made during December and not yet shared...

**Comment by AustinLeungCK** [comment]
thanks for the reply.
i just got all the resources from the repo yesterday, and i think its the latest / more recent version of the kexts.

**Comment by profzei** [comment]
@AustinLeungCK Now I clean up the repo... but release v. 1.8.0 is still present... if you downloaded my (outdated) repo zipping it in a single file yesterday you didn't download the release v. 1.8.0... and obviously you suffer the issues you mentioned

Please, check the right side menu for downloading releases
