### ISSUE TITLE
AggregateVolumeMenu

### ISSUE THREAD

**Issue by samueljoh** [profzei/Matebook-X-Pro-2018#146]
Maybe this could be used to make it possible to change Volume on both speakers. Instead of using Soundflower?

https://gurhanpolat.medium.com/change-volume-on-aggregate-sound-815fd575347a
https://github.com/adaskar/AggregateVolumeMenu

**Comment by profzei** [comment]
@samueljoh I'll check this new option in weekend! Thank you very much for your contribution

**Comment by profzei** [comment]
@samueljoh Now I'm using SoundSource with success!
I see that you opened a request on [https://github.com/adaskar/AggregateVolumeMenu](https://github.com/adaskar/AggregateVolumeMenu):
- AggregateVolumeApp is working fine on Catalina
- have you checked if F4, F5 & F6 hotkeys are working fine?

Could you please report here your feedback so that I can update/improve relative documentation?

**Comment by samueljoh** [comment]
Didn't know about SoundSource, looks like a great application. 

AggregateVolumeMenu is working fine on Catalina. I think you may have to select your Multi-Output as source in System Preferances or from the regular sound menu before you launch it.

The volume and mute keys (F4, F5 and F6) works as they should.

**Comment by profzei** [comment]
I just updated [guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Activate-Surround-Sound-via-MIDI-on-internal-speakers)! Thank you very much for your contribution!

**Comment by R-Teer** [comment]
Can confirm Soundsource as a great work around, been using it since Catalina to get volume keys for multioutput sound

**Comment by unverbraucht** [comment]
I applied it on Big Sur, works great!

**Comment by profzei** [comment]
> I applied it on Big Sur, works great!

@unverbraucht Great!
