### ISSUE TITLE
Grey screen with cursor after updating to Big Sur

### ISSUE THREAD

**Issue by BrandonVerstege** [profzei/Matebook-X-Pro-2018#148]
Using the instructions to update to Big Sur, I've now landed on this grey screen. Using the latest EFI release. USB installer went fine, then booted to macOS disk, rebooted once or twice, now I land at this grey screen whenever I boot from my macOS disk. Any suggestions? 2018 MXPro i7/MX150. The only changes I made to the config.plist was to change smbios values. Thanks in advance for any help.

**Comment by profzei** [comment]
@BrandonVerstege ...I really don't know... instructions to upgrade from Catalina to Big Sur were written during last summer but should be working fine also now. 
During this summer I created 2 EFI's folders: one for installation and one for post-installation: why? Since following Dortania's guide, I learned that "less is more" i.e. an EFI which is working fine after installation could not work well during installation!
Therefore I created a minimal EFI's folder for USB install  and then another EFI's folder for post-install.

What I could suggest is the following:
- read carefully Dortania's guide
- use my old minimal EFI's folder for USB install or create an updated version (I advise the latter step with updated kexts!)
- then, after a successful install, copy EFI's folder from USB to your EFI's disk and reboot your system: obviously not all devices will work fine but it's only one reboot!
- finally you can update to the latest release in this repo

Let me know your feddback!

**Comment by profzei** [comment]
I just updated to BS without any issues in November...
