### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#15]
Hi mate!
First of all, great work! I'm having problem with sound devices. In system preferences I have two devices as you can see in the image:
![image](https://user-images.githubusercontent.com/37642427/83916645-eb486f00-a74b-11ea-84ec-c247a86d7c6c.png)
At first I thought it was just a glitch, but then when it comes to have calls with zoom, hangout or whathever, at cetain time the sound goes to the other device, so I have to switch between them everytime the sound stops. Also the headset microphone does not work (plugged via jack port).

**Comment by profzei** [comment]
Hi, for the headset have you tried [ALCPlufFix](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/ALCPlugFix) from this repo?
The duplication of the device could be due to the fact that our card has four channels... I have not found any guide to configure a sound card with AppleALC from scratch... do you know any of them? I saw that our configuration [(release 1.4.1)](https://github.com/acidanthera/AppleALC/releases) was submitted by DalianSky so it should be ok...

**Comment by hdamico** [comment]
Tried ALCPlugFix but the script is broken, throws you a 404 error.

**Comment by edrevpac** [comment]
Hello, 

First off, DISCLAIMER: I am not using the audio jack for input/output so the usefulness of the below might be limited for you, but it might stop switching audio sources mid-meeting.

You can try to create a new Aggregate Device in the MIDI Audio Devices, assign both "Internal Speakers" to it, and, under "Configure Speakers", select "Quadraphonic" as setup - this will allow 4.0 positional audio. You will still have to adjust speaker volume individually for each "Internal Device".
You can also associate the MIC to this Aggregate device so that audio and noise detection/cancellation works as expected in meetings. I am using this setup with WebEx and Google Meet and it works well.

Let me know if this works for you.

**Comment by hdamico** [comment]
Hello @edrevpac!,

Thanks for the suggestion, I will check it as soon as I have another call.

**Comment by hdamico** [comment]
@profzei get it work by changing `https://raw.githubusercontent.com/profzei/ALCPlugFix/alc_fix/ALCPlugFix` to
`https://raw.githubusercontent.com/profzei/ALCPlugFix/master/alc_fix/ALCPlugFix`

**Comment by yichebb** [comment]
> Anyway I still see two internal speakers

ALC256 layout-id 76 (4CH) for Matebook X Pro 2019 by Durian-Life (added in [release 1.5.0](https://github.com/acidanthera/AppleALC/releases/tag/1.5.0)) should fix this as it has 4 channels, which would negate the need for the workaround as mentioned by @edrevpac.
