### ISSUE TITLE
imessage- can't login

### ISSUE THREAD

**Issue by hiyurun** [profzei/Matebook-X-Pro-2018#151]
On big sur 11.2.1. I can't login to my imessage. It boots me out after a few seconds. Changed serial number, reset nvram. Anything else i can try out?

thanks!

**Comment by profzei** [comment]
@hiyurun Probably you need to enter your iCloud account, dissociate any previously associated MacBookPro device (which is how our MateBook X Pro is registered on your account), reboot your machine and then reassociate your device... I'm not sure since iMessage worked well for me from my first try so I didn't develop any particular debugging skill on this item!

**Comment by hiyurun** [comment]
i just tried. Doesn't work

**Comment by profzei** [comment]
@hiyurun ...Then I don't know, I'm sorry but this is not an issue due or related to the config present in this repo...
