### ISSUE TITLE
Can't boot to windows 10

### ISSUE THREAD

**Issue by jeffreyouni** [profzei/Matebook-X-Pro-2018#154]
Hello,
How are you?
I just put your BOOT and OC file into EFI.
I boot to macOS successfully but it will stick on loading windows.
Could you tell me how to fix this?
Thank you very much!

**Comment by unverbraucht** [comment]
Hi,

I had a similar problem. I also have that on another computer (not a Matebook) where I have multiple operating systems installed, maybe the EFI system got confused with the boot entries or something.

What helped me solve this was following the steps here: https://www.reddit.com/r/hackintosh/comments/fj3zrj/booting_opencore_without_the_usb_on_an_asrock/

**Comment by profzei** [comment]
@unverbraucht You said "I had a similar problem." 
Does this mean you have actually a dual booting system (macOS + Windows) where you can boot Windows from OpenCore boot picker menu using my latest release?

Honestly, using my latest release but also previous ones I'm not able to boot Windows from OpenCore boot picker... (no problem from BIOS boot menu invoked with `F12`) I always thought this should be related, in my very specific case, to the fact that 
- I really messed up some months ago my EFI partition
- so then I was forced to recreate it without reinstalling neither Windows nor macOS but only using Windows `diskpart` command tool
- probably I missed some fundamental attribute in the creation process...

@unverbraucht I didn't know the guide you shared here, but I appreciate it very much: I'm very interested in digging more my case since I had a lot of experience with Linux OS

**Comment by espitgn** [comment]
Thanks @profzei for your hard work. It's the best hackintosh I've had!

I had the same issue with 2.0.0 and 2.1.0 releases (when windows is selected, starts booting for 1 sec, and then the system reboots). I could fix it using rEFind menu, but finally I decided to come back to 1.9.1 (with OC 0.6.5). In this release windows works without issue. Could it be a problem related with new boot feature in OC 0.6.6.?

**Comment by profzei** [comment]
> Could it be a problem related with new boot feature in OC 0.6.6.?

@espitgn Honestly I don't know... probably I guess I didn't protect in the right way some patches I wrote between 1.9.1 and 2.0.0-2.1.0... I need to re-check them... honestly during Easter's holidays not before since I have too many deadlines...

**Comment by espitgn** [comment]
Please, don't worry! I'm very comfortable with 1.9.1 release. Have a good Easter's holidays!

**Comment by rohirrim27** [comment]
Seconding espitgn's observation - I had difficulties (recovery and restart) in booting into windows on my dual-boot (via 2 separate SSDs) system since updating to 2.1.0 (and OpenCore 0.6.7).

Everything else is working great thanks to you but do you think this could be due to the "Windows Activation failure due to different hardware UUID generated by OpenCore" you mention on the homepage? I'm testing injecting the original Windows UUID into the config.plist as you suggested but would be great if you could share more on that? I scanned the OpenCore Official Configuration PDF but couldn't find more details on the process.

**Comment by profzei** [comment]
@rohirrim27 

> Seconding espitgn's observation - I had difficulties (recovery and restart) in booting into windows on my dual-boot (via 2 separate SSDs) system since updating to 2.1.0 (and OpenCore 0.6.7).

I need to check whether I protected in the right way all the patches... probably not! I'll start working on this item next Thursday...

> Everything else is working great thanks to you but do you think this could be due to the "Windows Activation failure due to different hardware UUID generated by OpenCore" you mention on the homepage? I'm testing injecting the original Windows UUID into the config.plist as you suggested but would be great if you could share more on that? I scanned the OpenCore Official Configuration PDF but couldn't find more details on the process.

Honestly I remember I found that procedure in a bug report in acidanthera bug tracker almost one year ago I suppose (...now I'm not able to find it using Google... I also remember it was discussed on some Reddit posts...)

**Comment by rohirrim27** [comment]
Thank you profzei! Really appreciate all you do for us!

**Comment by supremekiind** [comment]
Hey Profzei, i found an Solution from BenDevelopment:

"There are the solutions I know:
First: adding If (_OSI ("Darwin")) in all ssdt.
Second: don't use OpenCore for boot selection."

Can you help me with the first solution? I dont know how to edit the ssdt`s.

Thank you very much 
Supremekiind

**Comment by profzei** [comment]
@supremekiind 
> probably I guess I didn't protect in the right way some patches I wrote between 1.9.1 and 2.0.0-2.1.0... I need to re-check them... 

Your "first solution" is what I mean using the expression **protect in the right way** ... it's the basic level for writing patches.
Honestly, since I'm a teacher now 

> I have too many deadlines...

Therefore I'm working on this item during my spare time...

**Comment by profzei** [comment]
@gnodipac886 Thank you for the hint!

@jeffreyouni @espitgn @rohirrim27 @supremekiind @gnodipac886 
**Now** I think I **totally** fixed Windows 10 booting issue: I have done 10 successful dual-booting iterations till now without any issues...

Since I don't know if next OpenCore 0.7.0 will be released on Tuesday 1 June (it's not first Monday in June...) or Monday 7 June, I prefer to just check some other little things and make a **"fixing" release late today or tomorrow**...

**Comment by profzei** [comment]
Please, check new [Release v. 2.3.0](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v2.3.0) and let me know your feedback!

**Comment by jeffreyouni** [comment]
> Please, check new [Release v. 2.3.0](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v2.3.0) and let me know your feedback!

Hello, Profzei
I have installed your 2.3.0 version and it solved all the problems.
Thank you for your upgrade!

**Comment by espitgn** [comment]
> Please, check new [Release v. 2.3.0](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v2.3.0) and let me know your feedback!

Hi, Profzei

Booting and working with 2.3.0. in Windows without  issue! Thanks for you work!
