### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by supremekiind** [profzei/Matebook-X-Pro-2018#158]
Hey Profzei really like your work and Thank you :D My only two problems is the known issue with WIndows and a strange Performance issue. I have same Lap like you (16Gb of ram) but only get about 3100 Bench score... do you get an idea what the problem is? Sorry for bad english only have it at German-school. Thank you very much and have nice vacation. 

<img width="901" alt="Bildschirmfoto 2021-03-28 um 13 21 20" src="https://user-images.githubusercontent.com/74076799/112750503-48f2c400-8fc9-11eb-9495-63f8cc0e83ec.png">

**Comment by profzei** [comment]
@supremekiind 
Hi, here it is my actual value: [**4042**](https://browser.geekbench.com/v5/compute/2618370)
Why it is different from published one?
- different `Geekbench` version? i.e. 5.2.4 (published one) vs 5.3.1 (my actual value) vs 5.4.0 (your value)? ...I really don't think this could be relevant...
- different `SMBIOS`? Now I'm using **MacBookPro14,1** while in October I was on **MacBookPro15,2**
- different macOS versions? i.e. **Catalina 10.15.7** vs **Big Sur 11.2.3**? ...I don't think there should be a such great gap... but **it's only my opinion**...
- maybe because now my tests are with **undervolting feature on** while honestly I don't remember whether it was on for published benchmark? ...**It could be!** Honestly I think this is the right answer at least in my case since I'm undervolting not only CPU but also GPU even if slightly...

You could try to analyse deeper each possibility! ;-)

**Comment by supremekiind** [comment]
@profzei 
Hey, I tested your possibilities but don't get an answer...

I notice that I got a score of 4500 but only in very special constelation. I reinstalled and got it one time but when boot its gone. But I got it with randomness after install but don't know how. Do you have another clue? 
Thanks for your work anyway and have nice day. :)

**Comment by profzei** [comment]
@supremekiind Honestly I don't know... I'm sorry

**Comment by supremekiind** [comment]
Its not the SMBIOS got later the day same bad Score. Anyway don't know what's the problem, if anyone other got same Issue and a Fix please mark me (@) Thanks to everybody in this thread.

**Comment by supremekiind** [comment]
Hello i am very confused... now with Smbios from a Mac Pro it works stable with 4000-4500 🤔 I also noticed that NVRam reset partially has fixed low performance issue.I dont know what to say  :( 
Bye and have a nice day
