### ISSUE TITLE
Caps Lock and Fn keyboard LED turns on when computer sleeps

### ISSUE THREAD

**Issue by giulioverazzo** [profzei/Matebook-X-Pro-2018#159]
Hi, first of all thank you so much for your work! 

I have a Matebook X Pro 2018 with Big Sur 11.2.3 installed and working just fine.

There is just one thing that I'd like to solve: when the pc is put in sleep mode either from the the apple menu or by closing the lid, the caps lock and Fn LEDs on the keyboard turns on and when the pc is resumed they turn off again. If the are already on they stays active.

Is there something that can be done to prevent this to happening?

Wish you a good day and thanks again!

**Comment by profzei** [comment]
@giulioverazzo Hi! What you are referring about should not be an issue...

- Have you followed/applied the settings in **Sleep & Hibernation section** in homepage?
- Are you using **Soundflower** for creating your aggregate audio device?

If answer is positive for the first one and negative for the latter, then I guess the cause should be only an app I'm not using...
You could check the reason for a failed sleep typing in **Terminal**
```sudo pmset -g assertions```
but the output isn't lightning in general because it refers to the core service used and not to the app which is using a such service.

**Comment by BigEmperor26** [comment]
That is the default behaviour in Windows too. I don't know why it's like this, but it's probably some way to immediately tell the user that the machine is not off but sleeping.
