### ISSUE TITLE
Little Thing - Double Tap and Drag

### ISSUE THREAD

**Issue by supremekiind** [profzei/Matebook-X-Pro-2018#164]
Hey @profzei

Another little thing. Do you know how to easily enable double Tap and Drag like its found on real Mac as I know.

Thank you :3

**Comment by profzei** [comment]
@supremekiind I really don't know since I do not use it... so I **only googled** just for curiosity... Here it is the first result:
[https://apple.stackexchange.com/questions/374138/how-to-enable-double-tap-to-drag-in-mac-os-x-catalina](https://apple.stackexchange.com/questions/374138/how-to-enable-double-tap-to-drag-in-mac-os-x-catalina)
Don't know if it is still valid for BS!

**Comment by unverbraucht** [comment]
Yes, that’s exactly the way, I also use it exclusively on all my Macs. It works quite well also with the slightly wobbly trackpad in the Matebook.

**Comment by supremekiind** [comment]
Thank you man :3
