### ISSUE TITLE
[question] Big Sur 11.3

### ISSUE THREAD

**Issue by PLTorrent** [profzei/Matebook-X-Pro-2018#165]
Hi,

Just a question. I can see that you have listed 11.3 in the repo. However the latest release is from March and you advise not to use a main repo. Will there be a new release soon supporting 11.3? I saw that a couple of things have been updated since March.

Regards

**Comment by profzei** [comment]
@PLTorrent 
Yes! I'll make a maintenance release very soon (there are no significant changes for ACPI stuff), but if you like you could just update Kexts folder and then update to Big Sur 11.3... my update was flawlessly smooth!😁

I'm waiting because OpenCore 0.6.8 didn't introduce relevant changes under the hood apart OpenCanopy cosmetics support... so I'm waiting for 0.6.9 release

**Comment by PLTorrent** [comment]
@profzei thanks for the swift response. I’ll probably wait for the official release. I’ve seen that some people on hackintoshes had issues with USB port mapping. I understand that this will work on MXP after update without issues?

**Comment by profzei** [comment]
> I’ve seen that some people on hackintoshes had issues with USB port mapping. I understand that this will work on MXP after update without issues?

@PLTorrent All our USB ports are working fine without any other tweaking

**Comment by PLTorrent** [comment]
@profzei  I know I could but to be honest since you've set up your repo I got a bit rusty on hackintoshing :) I don't feel like searching all those kexts an stuff. I'll just wait for the official update and then upgrade macos to 11.3 :)

**Comment by PLTorrent** [comment]
Thank you for the release :)
