### ISSUE TITLE
Maybe you know(audio on similar model)

### ISSUE THREAD

**Issue by Edoardo001** [profzei/Matebook-X-Pro-2018#19]
Hi, man. Congrats for your awesome work. I've done something similar for matebook 13(alc256 too). Unfortunately we got camera and audio jack not working. For the camera I know that maybe it's just not compatible and it's ok.

But for the audio even we made layout by dumping codec from Linux, we got headphones jack not working. So I wanna know if your has been worked out of the box(even bad) after layout choosing , because ours headphones jack it's totally ineffective, no one signal, nothing(even with combojack fix)

Thanks in advance

**Comment by profzei** [comment]
Hi,
I just used layout-id=97 made by daliansky for matebook x pro... and both speakers and headphone's jack worked... we have an issue probably due to the fact that our audio card has 4 channels but I didn't find any guide for building a new "profile" for AppleALC for testing how good is our actual profile...
Did you find any good and updated guide?
Have you tried[ ALCPlugFix](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/ALCPlugFix) for fixing the switch between headphone's jack and internal speakers?

**Comment by Edoardo001** [comment]
> Hi,
> I just used layout-id=97 made by daliansky for matebook x pro... and both speakers and headphone's jack worked... we have an issue probably due to the fact that our audio card has 4 channels but I didn't find any guide for building a new "profile" for AppleALC for testing how good is our actual profile...
> Did you find any good and updated guide?
> Have you tried[ ALCPlugFix](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/ALCPlugFix) for fixing the switch between headphone's jack and internal speakers?

Many thanks for your attention. I've tryie ALCPlugFix but with no luck. Our problem is not to switch between headphones and internal speaker, we have only one audio output source 😭. ALCPlugFix is only to switch automatically between headphones and internal and for audio distortion, right? 

The only layout that show me both internal and headphones is the 28, and ALCPlugFix fix the audio distortion. But this layout has 2 problems
1-  preselected audio output at boot is the audio jack, so I gotta switch every boot.

2- internal mic, won't work
