### ISSUE TITLE
3.1.0 Crash after 1-2 mins of startup

### ISSUE THREAD

**Issue by rohirrim27** [profzei/Matebook-X-Pro-2018#194]
Hi @profzei,

Thank you for working on and releasing 3.1.0 which I'm sure addresses the challenges a few people were experiencing with 3.0.0.

However, as I didn't update to 3.0.0 and am testing out 3.1.0, not sure if the following is a new issue or needs me to make changes on my end. I've followed the updated ReadMe step by step but the laptop crashes and restarts every 2 mins with the following Apple Error Report (sorry for the pictures, wasn't able to take a screenshot and send in time).

![WhatsApp Image 2021-10-19 at 3 22 50 PM](https://user-images.githubusercontent.com/75772430/137862608-cc6df6cd-8598-4715-8251-52aa75edbdd0.jpeg)
![WhatsApp Image 2021-10-19 at 3 22 49 PM](https://user-images.githubusercontent.com/75772430/137862557-c90f1bf3-29c9-405c-ab27-bae8a62abe0f.jpeg)

I've been using a dual booting system with Windows on the internal SSD and Mac OS installed on the external SSD and it's been working flawlessly thanks to you till date.

**Comment by profzei** [comment]
@PLTorrent 

**Thank you very much for your precious collaboration**!... if possible I would like to take advantage of it again to try to "understand" better...

The function `pci-aspm-default` is used to activate for macOS **Active-State Power Management** for pci (also express) devices like:
- `PciRoot(0x0)/Pci(0x1c,0x0)` which is PCI-Express bus for nVIDIA card
- `PciRoot(0x0)/Pci(0x1c,0x4)` which is PCI-Express bus for LiteON SSD
- `PciRoot(0x0)/Pci(0x1d,0x0)` which is PCI-Express bus for Thunderbolt Controller
and therefore optimize power consumption for these buses

We need to point out that macOS is an OS which is designed for working well/optimally only on Mac hardware, so in our hackintoshes it could be advisable to force a such property whenever possible... 

How we could say if a such feature is working fine or is supported for our hardware?
Simple: if the device does not support `ASPM`, then the operating system may freeze: I checked (during this summer) that my machine didn't suffer any issue...

So, why did this issue affect your device and others?
- Thunderbolt Controller must be the same...
- nVIDIA card must be the same...
- SSD could be different: this is why I suggested to some user to disable this feature...

1. Could you check, please, that you need to remove ALL those properties?
2. Could you report, please, your BIOS version? 

Power management properties could be changed/optimized with newer BIOS version (even if ACPI `DSDT` is essentially the same...), even if, in a such case, it seems to me, we could talk about a **regression** because in my case adding a such property was not harmful which means that `ASPM` is supported and working fine... issues are only for devices **NOT** supporting well `ASPM`...
