### ISSUE TITLE
Can’t installing Catalina on matebook x pro 2018

### ISSUE THREAD

**Issue by Hai2332** [profzei/Matebook-X-Pro-2018#205]
Hello,

Thank you about your amazing work!
I am trying to install macos (catalina) on my MbXpro 2018 on external Toshiba hdd.
Every time I finished installation, the pc do a reboot and get into installing process again.
I’m not sure if I make the usb right.
Any suggestions?

Thanks!!!!

**Comment by profzei** [comment]
Hi,
Honestly I don't know since it is a lot of time I'm not using Catalina on MBXP... and therefore I didn't test latest OpenCore security features on it...

**Comment by Hai2332** [comment]
> Hi,
> Honestly I don't know since it is a lot of time I'm not using Catalina on MBXP... and therefore I didn't test latest OpenCore security features on it...

Tnx for your comment!
The truth is I do not care which version,Catalina/Big Sur or whatever….
 I just want to be able to install the hackintosh on the computer.  Can you explain to me how? 
 I'm also willing to pay lol 😂

**Comment by profzei** [comment]
> I'm also willing to pay lol

Honestly, you don't need to pay for getting a reasonable support from me or anyone reading this thread and with more experience on installing on external devices...

However if you find the `EFI` developed in this repo useful, then you could click on the "buy me a coffee" banner on repo's homepage...

"Probably" for Catalina you need to add to your `config.plist` also these changes:
```
<key>UEFI</key>
<dict>
    <key>APFS</key>
    <dict>
        ...
        <key>MinDate</key>
	<integer>-1</integer>
	<key>MinVersion</key>
	<integer>-1</integer>
        ...
```

However, for Big Sur I can assure that all you need is explained [here](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Installing-macOS) which is the guide linked on this repo's homepage...

Since you stated that you reached the end of installation process, I guess you build a proper usbpen for installing macOS!

Just one more hint: since you are installing on an external device and, as stated in my homepage, on `default` config Thunderbolt controller support is dropped, it could be not a smart idea using thunderbolt port for installing macOS...

**Comment by Hai2332** [comment]
> 

I will try to install big sur, but in gibmacos there is no full install for this version, so what to do?  
And as for the external drive, are you implying that it is not possible to install on an external drive?
 Or just need to enable the usb type c connection? 
 thank you for your time!!

**Comment by profzei** [comment]
Honestly it's a long time I do not use `gibMacOS` strategy for installing macOS... in fact it is no more mentioned in Dortania's guide...

I guess you have no access to a real or virtualized Mac for building your usbpen... this means you could use from Windows
- [balenaEtcher](https://www.balena.io/etcher/) for flashing `dmg` macOS image
- then use Google for getting a Big Sur `dmg` image, for example from [https://themacgo.com/macos-big-sur-11-5-1-dmg-download-issue-fix-direct-link/](https://themacgo.com/macos-big-sur-11-5-1-dmg-download-issue-fix-direct-link/)
- you could install Big Sur using the EFI released in this repo and, if all goes fine (it should! XD), then you could update to latest 11.6.2 using `System Preferences -> Software Update` inside macOS

**Comment by Hai2332** [comment]
> Honestly it's a long time I do not use `gibMacOS` strategy for installing macOS... in fact it is no more mentioned in Dortania's guide...
> 
> I guess you have no access to a real or virtualized Mac for building your usbpen... this means you could use from Windows
> 
> * [balenaEtcher](https://www.balena.io/etcher/) for flashing `dmg` macOS image
> * then use Google for getting a Big Sur `dmg` image, for example from https://themacgo.com/macos-big-sur-11-5-1-dmg-download-issue-fix-direct-link/
> * you could install Big Sur using the EFI released in this repo and, if all goes fine (it should! XD), then you could update to latest 11.6.2 using `System Preferences -> Software Update` inside macOS

My girlfriend have MacBook Pro 2019, its better?
And as for EFi, how do I set all the data I need inside the config file?
Thanks

**Comment by profzei** [comment]
> My girlfriend have MacBook Pro 2019, its better?

If you have access to a real Mac then you could follow step-by-step previously linked guide... ;-)

> how do I set all the data I need inside the config file?

You need to use an editor for `plist` files, for example:
- [ProperTree](https://github.com/corpnewt/ProperTree) as suggested in Dortania's guide
- [Sublime Text](https://www.sublimetext.com) which is my favorite one!
- any Markdown editor is good...

**Comment by Hai2332** [comment]
> > My girlfriend have MacBook Pro 2019, its better?
> 
> **Edit**: It is an Intel-based one, isn't it? If so, then (you can continue reading...) If you have access to a real Mac then you could follow step-by-step previously linked guide... ;-)
> 
> > how do I set all the data I need inside the config file?
> 
> You need to use an editor for `plist` files, for example:
> 
> * [ProperTree](https://github.com/corpnewt/ProperTree) as suggested in Dortania's guide
> * [Sublime Text](https://www.sublimetext.com) which is my favorite one!
> * any Markdown editor is good...

I did not understand what is different whether I use a Mac or Windows. 
 Regarding the config file I know how to edit it, but I did not understand by what, according to all the lines in the installation guide? 
And what about gmbios?  Need the details of my computer?

Thanks

**Comment by Hai2332** [comment]
Hello friend, I finally installed big sur on my computer.
I've got two questions.
1. Is there a way to make the airdrop work?
2. It is currently installed on an external disk, if I want to install on the internal disk I need to lose the information of in windows?
Thank you so much for your amazing work!

**Comment by profzei** [comment]
Hi @Hai2332 ,
I'm glad you succeeded in installing BS.

1. this is the best achievable with an Intel card: device could be discoverable but connection is not garanteeded: I cannot do anything since it relies on `AirportItlwm.kext` development
2. It's very simple and you can find also videos for dual booting: as I wrote in my guide linked [here](https://github.com/profzei/Matebook-X-Pro-2018/issues/205#issuecomment-1003725144) you only need to resize your Windows partition and your EFI partition and reinstalling os... how? You could find references on Dortania's guide or there are many other guides on web... or if you prefer and are capable you could clone your installation... how? there are many other guides on web or YouTube
