### ISSUE TITLE
Reboot when cover the screen

### ISSUE THREAD

**Issue by kxlv2000** [profzei/Matebook-X-Pro-2018#21]
Hi, there

Recently, I have found that my computer has come across some problems. macOS will reboot when the screen off. Before I weak it up, the system has already rebooted and show me a failure information at desktop. Windows as well as applications has already recovered like before failure. Here is my [panic log.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/4784149/panic.log.txt).
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/49295281/84726908-7cc3a680-afc0-11ea-80fc-63212a88fcc8.png">

I have executed your commend about "Power management: Hibernation", it seems that there is something wrong with IOUSBHostFamily. the system went to failure after 180 seconds screen off. Do you have any idea about this? Thanks!

**Comment by PLTorrent** [comment]
Setting in bios „other wakeup source” to disabled might help

**Comment by profzei** [comment]
Hi @kxlv2000  @PLTorrent , try [my latest release v. 1.2.0](https://github.com/profzei/Matebook-X-Pro-2018/releases): the issue should be fixed!
Please, don't set in BIOS the option "Other wakeup sources" as disabled otherwise waking up the machine opening its lid should not be possible!
Let me know your feedback!

**Comment by kxlv2000** [comment]
Thanks, I have tried, it seems working properly till now.
