### ISSUE TITLE
Left USB-C Thunderbolt port not working properly

### ISSUE THREAD

**Issue by bmmund** [profzei/Matebook-X-Pro-2018#23]
I am observing some interesting behaviour with the thunderbolt port. When I boot up with nothing plugged in and try to connect a storage device to that port no device is connected. However, USB HID devices work (keyboard, mouse) as expected.

More interestingly, if I start with the computer off and the storage device plugged in and then boot into OSX, the device will be connected and will show up. If I unplug and plug back in the storage device it will not show up as a connected device.

**Comment by PLTorrent** [comment]
This is normal thunderbolt behavior on hackintosh AFAIK. Also I think there is no known workaround for this.

**Comment by benbender** [comment]
Just as a hint: Your HID-Devices and similar aren't really thunderbolt, but very likely usb. The connector is usb-c and it can do multiple protocols (TB, USB 2/3/3.1, DP, etc) with different backing controllers. 

The problem on hackintoshes is mostly about TB on usb-c, because the firmware and power management of apple's TB-controllers works entirely different than those for other OS'es. So even if it's the same hardware found on windows laptops, they don't "just work" because of the different firmware.

Some attempts to fix this by patching the firmware can be found here: https://github.com/osy86/ThunderboltPatcher
