### ISSUE TITLE
Sidecar not working

### ISSUE THREAD

**Issue by Talal916** [profzei/Matebook-X-Pro-2018#24]
My 2019 iPad Pro does not show up on Sidecar when connected over wire. It used to work wired on Gnodipac's build and I believe your old Clover build as well. Wifi/BT both working and able to connect to iPad for transferring music/files, but not showing up in Sidecar dropdown. Have tried in both type C ports. 

![image](https://user-images.githubusercontent.com/36909014/85562994-d724be80-b5e1-11ea-9f93-de6f8044d5e0.png)

**Comment by profzei** [comment]
Hi @Talal916, as stated [here](https://support.apple.com/en-us/HT210380#systemrequirements) your iPad needs to be set to trust your Mac... and you maintained SMBIOS info only for the "SystemProductName" as MacBookPro14,1 but you generated new values for ALL other info: for iPad you have a new "not trusted" machine.
Read carefully [here](https://support.apple.com/en-gb/HT202778#change) to reset trusted devices!

Otherwise, if you have a backup of your Clover's config.plist, please, just copy the relevant info in OC config.plist as suggested in step 3 of my [guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Converting-from-Clover-to-OpenCore)

**Comment by Talal916** [comment]
Hi @profzei , I reset the trusted devices and it still doesn't give me the Trust prompt. 

As for the Clover config, mine did not have any of the relevant info, I'm not sure where it was even pulling the serial numbers from since my Clover backup config.plist definitely does not have it.

**Comment by kilgil27** [comment]
I have my iPad showing up in sidecar wirelessly, but I get "the device timed out" when trying to connect. I cannot get it to recognize my iPad when plugged in with a cable...

**Comment by profzei** [comment]
@kilgil27 A question: are you using AirportItlwm.kext or itlwm.kext?
