### ISSUE TITLE
Trackpad doesn't work anymore

### ISSUE THREAD

**Issue by Roshaanv** [profzei/Matebook-X-Pro-2018#4]
Hi,

First of all, thank you for your work on Matebook Hackintosh. I really appreciate it.
Now to my problem: Everytime I replace the old files with the new ones (11.05.2020) the Trackpad stops working. I then have to copy over the old files to get it working again. I don't know if this is the case for only my Matebook or others too. I also get log output when I start or shutdown my Matebook.

EDIT: Added a picture of the log on startup where it mentioned a voodooi2c warning. Could perhaps say something about the problem. The quality isn't great, because I extracted the picture from my smartphone's slo-mo recording in low light. If there is a way to get the log file, let me know and I will add it.

![voodoo error](https://user-images.githubusercontent.com/33832843/81739711-19fc5e00-949c-11ea-9c9c-34cc6c1423b2.jpg)

Any ideas where the problem might be?

**Comment by profzei** [comment]
Hi,
The situation of long boot times and trackpad not functioning occurred also to me sometimes but only when I modified the Intel framebuffer... I think it may occur when there is a big discrepancy between what NVRAM expects and what is loading... but I'm not sure...

What do I do in such a situation? I just use an old usb mouse like during a standard macOS installation. Then I entered the machine, I shutdown it, I disconnected the usb mouse and finally I powered on the machine itself.

Then the boot process went fine and smooth.

I didn't investigated much the situation after a proper boot (since the touchpad worked very well, imho, during normal use) but now I will check whether those warnings occur also to me!
What I can say is that, for example, the last version of VoodooI2C & company fixes a lot of little issues: do you have updated your kexts folder to the last one, indipendently of  config-catalina.plist?

Sorry for my bad english...

**Comment by Roshaanv** [comment]
> Hi,
> The situation of long boot times and trackpad not functioning occurred also to me sometimes but only when I modified the Intel framebuffer... I think it may occur when there is a big discrepancy between what NVRAM expects and what is loading... but I'm not sure...
> 
> What do I do in such a situation? I just use an old usb mouse like during a standard macOS installation. Then I entered the machine, I shutdown it, I disconnected the usb mouse and finally I powered on the machine itself.
> 
> Then the boot process went fine and smooth.
> 
> I didn't investigated much the situation after a proper boot (since the touchpad worked very well, imho, during normal use) but now I will check whether those warnings occur also to me!
> What I can say is that, for example, the last version of VoodooI2C & company fixes a lot of little issues: do you have updated your kexts folder to the last one, indipendently of config-catalina.plist?
> 
> Sorry for my bad english...

I tried it with your usb mouse method, but it didn't work for me. I am currently using the voodoo from your repo. I will try to update voodoo and will let you know if it worked.

**Comment by profzei** [comment]
[sys_log_voodoo.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/4620737/sys_log_voodoo.txt)
Hi, I attached my last boot info.
I used the following command in terminal:
`log show --predicate 'process == "kernel"' --style syslog --source --debug --last boot > sys_log_voodoo.txt`

If I use TextEdit to search" Voodoo" info related (without "") I didn't see in my boot log anything wrong... so I'm not able to reproduce your issue at the moment...

Could your send me the result of the above mentioned terminal command, so I can inspect your boot strap, please?

**Comment by Roshaanv** [comment]
I have attached my log. I have noticed some differences, especially these lines:

`2020-05-13 10:37:22.469657+0200  localhost kernel[0]: (kernel) VoodooI2CSensorHubEnabler::INT33D0 Found Intel ACPI Sensor Hub Enabler
2020-05-13 10:37:22.480790+0200  localhost kernel[0]: (kernel) VoodooI2CSensorHubEnabler::INT33D0 Enabled Sensor Hub`

These lines exist in your boot log, but not in mine. There are more lines that are different further down in the log. I think it doesn't even start the I2C Controller on my Matebook.

[sys_log_Roshaanv.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/4621008/sys_log_Roshaanv.txt)

**Comment by profzei** [comment]
I checked your log... it's very different from mine...

Which CLOVER version are you booting from? is it 5116, like mine?
If not try to update CLOVER and then use my folder without the file  CLOVER/ACPI/patched/SSDT-TDP0.aml
The touchpad must work even without that file!

If all doesn't work, please, try to post ALL the CLOVER folder zipped.

**Comment by Roshaanv** [comment]
I had used 5108. Updated and tried it with 5116 & 5117 with and without 'SSDT-TPD0.aml', but still didn't work. 

I've attached my CLOVER folder here: 
[CLOVER.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4623865/CLOVER.zip)

**Comment by profzei** [comment]
This is my CLOVER folder:
[CLOVER.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4626600/CLOVER.zip)
Your structure is gnodipac886's one... I changed it following a more "Vanilla" one, but I don't know if it matters or not.
Try it as it is: config.plist file present in folder is for Catalina version.

**Comment by Roshaanv** [comment]
I've tested it with your CLOVER folder and got the same result. (With and without 'SSDT-TDP0.aml'). I've attached the boot log file. It looks better than the last one (it finds the "Intel ACPI Sensor Hub enabler" and looks generally more like yours), but still no working touchpad

[sys_log2_Roshaanv.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/4630398/sys_log2_Roshaanv.txt)

**Comment by AshleyMiller9696** [comment]
doesn't work for me either with your /Clover Folder
-> but works with the kext from gnodipac886

**Comment by profzei** [comment]
@AshleyMiller9696 are you referring to trackpad, isn't it?

**Comment by AshleyMiller9696** [comment]
correct
but thanks for updating this repo / hackintosh :)

**Comment by profzei** [comment]
@AshleyMiller9696 Sorry for the inconvenience! Now the repo is updated with "old" but functioning version of **VoodooI2C** and **VoodooI2CHID** (both at version **2.3**). If you look at VoodooI2C forum you should see a lot of troubles due to the fact that developers are rewriting all the code! So best is to stay with version 2.3!

**Please update the folder CLOVER/kexts/Other**

Today I also updated some other kexts (see https://github.com/profzei/Matebook-X-Pro-2018/blob/master/Changelog.md ) but they should be ok, since developers are tested them for 2 weeks...

**Comment by AshleyMiller9696** [comment]
Works!
-> Issue can be closed
