### ISSUE TITLE
Bluetooth doesn't work properly

### ISSUE THREAD

**Issue by juicypop** [profzei/Matebook-X-Pro-2018#6]
I just tried connecting my P30 Pro via Bluetooth and everything went smooth.

When I tried to send a file with Bluetooth I realized that the connection was gone. 

It'll connect for like 5 seconds and drop it immediately. 

I use your Clover folder with catalina plist on 10.15.4 install.

**Comment by hdamico** [comment]
AFAIK the bluetooth kext cames from [here](https://github.com/zxystd/IntelBluetoothFirmware), and is on beta. I had a lot of problems with these kext, so I deleted them and attached an external bluetooth dongle. Keep an eye on new updates in that repo.

**Comment by yamsboi** [comment]
Bluetooth is not persistent after sleep. I remember having this issue with gnodipacs build too. Is there a fix im missing?

**Comment by profzei** [comment]
Hi @yamsboi! This issue (even if it doesn't occurs to me very often...) is pretty standard because the bluetooth kext is on beta phase i.e. is not stable.
At the moment, there are no new updates in the [repo](https://github.com/zxystd/IntelBluetoothFirmware) linked by @hdamico ...
But **I'm working to two workarounds** for improving our experience... I agree with you: it could be very annoying if it happens very often...
