### ISSUE TITLE
Need help ironing out kinks!

### ISSUE THREAD

**Issue by Zephariael** [profzei/Matebook-X-Pro-2018#65]
Hello! 

First of all, huge thanks to Profzei for enabling us noobs to have hackintoshes as well. I've successfully installed Catalina 10.15.7 on my machine and it works amazingly well. 

This is just to ask some questions. 

How do I disable the touchscreen? Which .kext do I disable in config.plist?

I can't see voltageshift kext in config.plist. It's in the kext folder but I can't find it under that name in the config. Following the instructions on the site returns:

./voltageshift info
zsh: no such file or directory: ./voltageshift

Any solution to this? 

Thanks for the help in advance!

**Comment by profzei** [comment]
@Zephariael : 

> How do I disable the touchscreen? Which .kext do I disable in config.plist?

You don't need to disable any kext... See [here](https://github.com/profzei/Matebook-X-Pro-2018/issues/37)

> I can't see voltageshift kext in config.plist.

I just checked `config.plist` in release v. 1.6.0: it is there... just use `Command+F` for finding it and set its state to `Enabled`.
In order to use `voltageshift` command on `Terminal` app, try to download it and follow carefully instructions [here](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Undervolt-via-VoltageShift)

...my English is not very good, so I hope instructions would be clear enough...

**Comment by Zephariael** [comment]
Hello Profzei!

_**PROBLEM 1**_

The Voltageshift issue is SOLVED. The commands were not being recognized in terminal. The solution is to drag the voltageshift file to the terminal and then fill in other commands.

Example: 

/Applications/Utilities/voltageshift info


This works.

**_PROBLEM 2_**

The other problem with the touch screen is NOT SOLVED.

Using the v1.1.0 release SSDT disables touchscreen but stops trackpad from working until lid is closed and opened again. Any solution to this?

Thanks!
