### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by BerndGoetzKoenig** [profzei/Matebook-X-Pro-2018#67]
Hallo from Germany,
first i will say a big "Thank You" to you.

i am using catalina.

I have a problem with bluetooth. When i connect i can see the mouse, but when i connect it is lost a few seconds later and the coursor cannot be moved.

i tried to change the order of the kext, but no chance.  in the hackintool app i can see the the FW is loaded into the device 0x0A2B.

i have  second question. in the system report i can see no Thunderbolt hardware, i cannot test it, because i have not TB Hardware, but ist this correct?

 Can you help?

**Comment by profzei** [comment]
@BerndGoetzKoenig 

> i tried to change the order of the kext, but no chance. in the hackintool app i can see the the FW is loaded into the device 0x0A2B.

Same here... or **in any other hackintosh**! There is not good support for bluetooth mouse!

> in the system report i can see no Thunderbolt hardware

Also this is **standard** since you need to inject proper microcode into controller for TB **full** support! ...and this is far beyond my actual intentions since I have not any TB hardware!
