### ISSUE TITLE
High CPU Usage after Sleep -- Kernel_Task

### ISSUE THREAD

**Issue by tlefko** [profzei/Matebook-X-Pro-2018#73]
Hey, tested out your repo along with my clover repo to confirm a problem I already noticed. After sleep, or long sleeps (not every time it's intermittent) kernel_task will have exceptionally high usage between 100-300% and clock speeds will ramp up and temps increase. not sure of the cause of this issue

**Comment by profzei** [comment]
Hi, the possible causes are:
- macOS itself: there are a lot of references in many forums
- Clover itself... it's behaviour is different from OpenCore (it is not the same using same ACPI or kexts folders since what is under the hood is different...)
- you are using SMCBatteryManager instead of ACPIBatteryManager and you suffer from the well-known ClamshellStateChange issue which may determine high usage in kernel_task!
