### ISSUE TITLE
I got stuck on the Apple logo when AirportItlwm.kext turned on

### ISSUE THREAD

**Issue by Vatri91** [profzei/Matebook-X-Pro-2018#84]
Hi,
There is a problem with AirportItlwm.kext. Every time it changes to true, the computer catches a bootlop on the Apple logo.

**Comment by profzei** [comment]
@Vatri91 
Sorry, but more details are needed... since I'm using it now without any issues!
Two questions:
- have you also set `DmgLoading` to `Signed` and `SecureBootModel` to `Default` in Catalina as suggested in [Network section](https://github.com/profzei/Matebook-X-Pro-2018/tree/master/Network) **and disabled** `itlwm.kext` **loading** in `config.plist`?
- or are you using Big Sur Beta?

**Comment by AshleyMiller9696** [comment]
@Vatri91  what did you do to solve the problem?
I‘m on Big Sur

**Comment by profzei** [comment]
@AshleyMiller9696 
If you are on Big Sur you need to set `DmgLoading` to `Any` and `SecureBootModel` to `Disabled`
