### ISSUE TITLE
iMessage and apple services not working

### ISSUE THREAD

**Issue by JonnIEnglish** [profzei/Matebook-X-Pro-2018#90]
I have followed all the instructions to update the serial numbers with SMBIOS but after I log in to iMessage with my Apple ID, it seems to work but a while after I send a message an error comes up saying the message was not sent and then iMessage crashes out. Any help to fix this would be greatly appreciated.

Running: MacOS 11.0 Beta (20A5395g)

**Comment by Vatri91** [comment]
This could be a beta issue. Try to update the system to the final version.

**Comment by AshleyMiller9696** [comment]
+ wait
a new version from profzei should release in a couple of days

**Comment by JonnIEnglish** [comment]
Okay, cool. Makes sense. 
Do either of you have iMessage working?

**Comment by Vatri91** [comment]
If it upgrades the system without a new version of OpenCore, the system may have problems or may not turn on at all, but this is not always the case. I am using the repo from November 12 and everything works fine on the official version of Big Sur. There are no differences vs Catalina for me. Unfortunately, I am not able to check if iMessege will work on the official version, because I do not have an iPhone. I prefer smartphones from Oneplus

**Comment by JonnIEnglish** [comment]
I also prefer android smartphones and I have never nought anything from Apple, but I was trying to get Apple services working for the sole purpose of having a fully functional Hackintosh.
