### ISSUE TITLE
[Question] Big Sur

### ISSUE THREAD

**Issue by dgtvc** [profzei/Matebook-X-Pro-2018#94]
Hi all,

Simple question, I want to update Catalina 10.15.7 to Big Sur, but do I have to upgrade it using https://github.com/profzei/Matebook-X-Pro-2018/wiki/Upgrade-to-macOS-Big-Sur or I can just click on Convert Now in system updates? Cause second method it's not working right now and i'm stuck on loading Apple logo.

And will first method delete my personal stuff?

Thanks @profzei for your work and latest release!

**Comment by profzei** [comment]
@dgtvc Sorry but I really don't know what you mean with:

> I can just click on Convert Now i system updates?

However, I suggest:
- **first update to release 1.7** on Catalina and check if everything is ok (it should be ok since I tested it a lot...)
- **then** go to `System Preferences -> Software Update`, check the presence of a new release and click **Upgrade now**...

That is what I've done to update to BS: I did not make a clean install...

**Comment by dgtvc** [comment]
Sorry in my language it says Convert Now :D
I will tried do it one more time!

**Comment by dgtvc** [comment]
Okey, never mind, apple logo hangs for me about for 1 hour without progress for like 10 times. Then i created this issue and tried again. Now it works after first try. I didn't changed anything in my setting :D
